name = "abair"
version = "1.0.0"
licences = ["Apache-2.0"]
description = "A client for abair.ie's Gaeilge voice synthesis"

repository = { type = "github", user = "lpil", repo = "abair" }
links = [
  { title = "abair.ie", href = "https://www.abair.ie/" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
simplifile = ">= 2.4.0 and < 3.0.0"
